# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'rspec', '~> 3.11'

gem 'tty-prompt', '~> 0.23.1'

gem 'tty-font', '~> 0.5.0'

gem 'colorize', '~> 0.8.1'

gem 'tty-table', '~> 0.12.0'

gem 'rubocop', '~> 1.27'

gem 'json', '~> 2.6'

